services:
  postgres:
    image: postgres:latest
    container_name: hypnia_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./backend/.volumes/postgres/data:/var/lib/postgresql/data/
      - ./backend/init:/docker-entrypoint-initdb.d

  frontend:
      build:
        context: ./frontend
        dockerfile: dockerfile
      container_name: frontend_container
      ports:
        - "8080:80"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend_container
    ports:
      - "3000:3000"
    env_file:
      - .env