services:
  postgres:
    image: postgres:latest
    container_name: hypnia_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
      - ./init:/docker-entrypoint-initdb.d
